### ISSUE TITLE
Missing Chapter 1 test database

### ISSUE THREAD

**Issue by thedavefulton** [PacktPublishing/Spring-5.0-Projects#1]
Hi, I'm currently working through the project in chapter one, and there is supposed to be an h2_world.sql file in the src/test/resources directory, and neither the file nor the directory appears to be in the repo.

**Comment by Abin-Packt** [comment]
Hi @thedavefulton,I am looking into the issue and the code will be updated very soon. Thank you for bringing the issue to our notice

**Comment by Abin-Packt** [comment]
Hi @thedavefulton  Author has provided the updated code for Chapter01....I have uploaded it. Please check if this is working.

**Comment by Abin-Packt** [comment]
For now I am closing this, if you find any issue feel free to open it.
